datasources:
     - name: prometheus
       type: prometheus
       orgId: 1
       url: http://127.0.0.1:9090
       access: Browser
       basicAuth: false
       database: prometheus
       editable: true
       isDefault: true
