# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = [
  "github.com/ethereum/go-ethereum*",
  "github.com/tendermint/iavl"
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/tendermint/tendermint"
  source = "github.com/maticnetwork/tendermint"
  revision = "aa42854c513f4d2387d858ce84cda7e24e31ab22"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "^0.6.0"

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "~0.14.1"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "=v0.34.4"
