# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1


executors:
  golang:
    docker:
      # specify the version
      - image: circleci/golang:1.13
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/maticnetwork/heimdall


jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: 
          name: "Build binaries"
          command: make build
  
  # test:
  #   executor: golang
  #   steps:
  #     - checkout
  #     - run: 
  #         name: "Run testcases"
  #         command: go test -v ./...