global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['127.0.0.1:9100']

  - job_name: 'heimdall'
    scrape_interval: 5s
    static_configs:
    - targets: ['127.0.0.1:26660']
